### ISSUE TITLE
Success Stories

### ISSUE THREAD

**Issue by bhavyachopra99** [AkshadGawde/DDTech_SIPBN_Website#56]
dark theme overall but white cars and then dark text? does not match theme at all. would recommend coming up with a better UI for this.

@AkshadGawde consider redesigning it

**Comment by bhavyachopra99** [comment]
on local has some additional errors - 

<img width="799" alt="image" src="https://github.com/user-attachments/assets/b1c79623-c8de-44d7-8290-15cbc3465d6d">

**Comment by AkshadGawde** [comment]
fixed
