### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by bhavyachopra99** [AkshadGawde/DDTech_SIPBN_Website#57]
different sies of texts and logo. try keeping uniform
<img width="588" alt="image" src="https://github.com/user-attachments/assets/d4972387-8732-443d-a094-a9de93bf499e">

**Comment by bhavyachopra99** [comment]
@AkshadGawde is this working? I dont know for sure as the site is static
<img width="443" alt="image" src="https://github.com/user-attachments/assets/e52ce724-f161-4e1b-9dc8-f2a3c785f3d2">


I could see a response though
<img width="443" alt="image" src="https://github.com/user-attachments/assets/7f4dbc99-03e2-4a8e-bd00-7733791ad49d">

**Comment by AkshadGawde** [comment]
Newsletter is not working, client has asked us to keep it on hold.
